package paniertp2.view;

import javax.swing.*;
/**
 *
 * @author bc935220
 */
public class vueDesc extends javax.swing.JFrame {

    /**
     * Creates new form vueDesc
     */
    public vueDesc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ADD = new javax.swing.JButton();
        FruitsCOMBOBOX = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        Fruits = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        DEL = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        ADD.setText("+");
        jPanel1.add(ADD);

        jPanel1.add(FruitsCOMBOBOX);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(Fruits, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        DEL.setText("-");
        jPanel3.add(DEL, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify                     
    private javax.swing.JButton ADD;
    private javax.swing.JButton DEL;
    public javax.swing.JTextField Fruits;
    private javax.swing.JComboBox<String> FruitsCOMBOBOX;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration                   
}

